CREATE TABLE public.instagram_posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  status TEXT NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'review', 'scheduled', 'publishing', 'published', 'failed', 'archived')),
  source_article_id UUID REFERENCES public.content_articles(id) ON DELETE SET NULL,
  pillar TEXT NOT NULL,
  hook TEXT NOT NULL,
  caption TEXT NOT NULL,
  hashtags TEXT[] NOT NULL DEFAULT '{}',
  image_prompt TEXT NOT NULL,
  image_alt TEXT NOT NULL,
  image_path TEXT,
  image_url TEXT,
  quality_score INTEGER NOT NULL DEFAULT 0 CHECK (quality_score BETWEEN 0 AND 100),
  quality_checks JSONB NOT NULL DEFAULT '[]'::jsonb,
  model TEXT,
  image_model TEXT,
  prompt_version TEXT,
  scheduled_at TIMESTAMPTZ,
  published_at TIMESTAMPTZ,
  meta_creation_id TEXT,
  instagram_media_id TEXT,
  instagram_permalink TEXT,
  last_error TEXT,
  created_by_email TEXT NOT NULL,
  updated_by_email TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (status <> 'scheduled' OR scheduled_at IS NOT NULL),
  CHECK (status <> 'published' OR (published_at IS NOT NULL AND instagram_media_id IS NOT NULL))
);

CREATE INDEX instagram_posts_status_idx
  ON public.instagram_posts (status, scheduled_at, updated_at DESC);
CREATE INDEX instagram_posts_source_article_idx
  ON public.instagram_posts (source_article_id)
  WHERE source_article_id IS NOT NULL;

CREATE TABLE public.instagram_generation_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  run_type TEXT NOT NULL CHECK (run_type IN ('manual', 'daily')),
  run_date DATE,
  status TEXT NOT NULL DEFAULT 'running'
    CHECK (status IN ('running', 'completed', 'failed', 'skipped')),
  post_count INTEGER NOT NULL DEFAULT 0 CHECK (post_count BETWEEN 0 AND 5),
  post_ids UUID[] NOT NULL DEFAULT '{}',
  model TEXT NOT NULL,
  image_model TEXT NOT NULL,
  prompt_version TEXT NOT NULL,
  requested_by_email TEXT NOT NULL,
  error_message TEXT,
  input_tokens INTEGER,
  output_tokens INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX instagram_generation_daily_once_idx
  ON public.instagram_generation_runs (run_type, run_date)
  WHERE run_type = 'daily' AND run_date IS NOT NULL;

CREATE TABLE public.instagram_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id UUID REFERENCES public.instagram_posts(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  actor_email TEXT NOT NULL,
  details JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX instagram_audit_post_idx
  ON public.instagram_audit_log (post_id, created_at DESC);

CREATE TABLE public.instagram_studio_settings (
  id SMALLINT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  daily_draft_count INTEGER NOT NULL DEFAULT 1 CHECK (daily_draft_count = 1),
  default_publish_time TIME NOT NULL DEFAULT '10:00:00',
  timezone TEXT NOT NULL DEFAULT 'Asia/Kolkata',
  prompt_version TEXT NOT NULL DEFAULT 'instagram-v1',
  updated_by_email TEXT NOT NULL DEFAULT 'system@eazydatafix.com',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO public.instagram_studio_settings (id) VALUES (1)
ON CONFLICT (id) DO NOTHING;

-- The access token is copied from the server secret on first use, then kept here so
-- a refreshed token can replace it without exposing it to the browser. This table is
-- service-role-only and no token value is ever included in a dashboard response.
CREATE TABLE public.instagram_credentials (
  id SMALLINT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  access_token TEXT NOT NULL,
  instagram_user_id TEXT,
  instagram_username TEXT,
  token_expires_at TIMESTAMPTZ,
  last_verified_at TIMESTAMPTZ,
  last_refreshed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER instagram_posts_updated_at
BEFORE UPDATE ON public.instagram_posts
FOR EACH ROW EXECUTE FUNCTION public.content_studio_set_updated_at();

CREATE TRIGGER instagram_studio_settings_updated_at
BEFORE UPDATE ON public.instagram_studio_settings
FOR EACH ROW EXECUTE FUNCTION public.content_studio_set_updated_at();

CREATE TRIGGER instagram_credentials_updated_at
BEFORE UPDATE ON public.instagram_credentials
FOR EACH ROW EXECUTE FUNCTION public.content_studio_set_updated_at();

ALTER TABLE public.instagram_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.instagram_generation_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.instagram_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.instagram_studio_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.instagram_credentials ENABLE ROW LEVEL SECURITY;

GRANT ALL ON public.instagram_posts TO service_role;
GRANT ALL ON public.instagram_generation_runs TO service_role;
GRANT ALL ON public.instagram_audit_log TO service_role;
GRANT ALL ON public.instagram_studio_settings TO service_role;
GRANT ALL ON public.instagram_credentials TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.instagram_audit_log_id_seq TO service_role;
