CREATE TABLE public.content_articles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  status TEXT NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'review', 'scheduled', 'published', 'archived')),
  content_type TEXT NOT NULL DEFAULT 'educational'
    CHECK (content_type IN ('educational', 'product_tutorial', 'case_study', 'checklist')),
  pillar TEXT NOT NULL,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  primary_keyword TEXT NOT NULL,
  secondary_keywords TEXT[] NOT NULL DEFAULT '{}',
  search_intent TEXT NOT NULL DEFAULT 'informational'
    CHECK (search_intent IN ('informational', 'problem_solving', 'commercial', 'navigational')),
  excerpt TEXT NOT NULL,
  content_markdown TEXT NOT NULL,
  meta_title TEXT NOT NULL,
  meta_description TEXT NOT NULL,
  canonical_url TEXT,
  og_title TEXT NOT NULL,
  og_description TEXT NOT NULL,
  faq JSONB NOT NULL DEFAULT '[]'::jsonb,
  internal_links TEXT[] NOT NULL DEFAULT '{}',
  image_prompt TEXT NOT NULL DEFAULT '',
  image_alt TEXT NOT NULL DEFAULT '',
  cta_text TEXT NOT NULL DEFAULT 'Try EazyDataFix',
  cta_url TEXT NOT NULL DEFAULT '/docs/quickstart',
  source_items JSONB NOT NULL DEFAULT '[]'::jsonb,
  seo_score INTEGER NOT NULL DEFAULT 0 CHECK (seo_score BETWEEN 0 AND 100),
  quality_score INTEGER NOT NULL DEFAULT 0 CHECK (quality_score BETWEEN 0 AND 100),
  quality_checks JSONB NOT NULL DEFAULT '[]'::jsonb,
  model TEXT,
  prompt_version TEXT,
  scheduled_at TIMESTAMPTZ,
  published_at TIMESTAMPTZ,
  created_by_email TEXT NOT NULL,
  updated_by_email TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (status <> 'scheduled' OR scheduled_at IS NOT NULL),
  CHECK (status <> 'published' OR published_at IS NOT NULL)
);

CREATE INDEX content_articles_status_idx ON public.content_articles (status, published_at DESC);
CREATE INDEX content_articles_scheduled_idx ON public.content_articles (scheduled_at)
  WHERE status = 'scheduled';
CREATE INDEX content_articles_primary_keyword_idx ON public.content_articles (lower(primary_keyword));

CREATE TABLE public.content_generation_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  run_type TEXT NOT NULL CHECK (run_type IN ('manual', 'daily')),
  run_date DATE,
  status TEXT NOT NULL DEFAULT 'running'
    CHECK (status IN ('running', 'completed', 'partial', 'failed', 'skipped')),
  article_count INTEGER NOT NULL DEFAULT 0 CHECK (article_count BETWEEN 0 AND 10),
  article_ids UUID[] NOT NULL DEFAULT '{}',
  model TEXT NOT NULL,
  prompt_version TEXT NOT NULL,
  requested_by_email TEXT NOT NULL,
  error_message TEXT,
  input_tokens INTEGER,
  output_tokens INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX content_generation_daily_once_idx
  ON public.content_generation_runs (run_type, run_date)
  WHERE run_type = 'daily' AND run_date IS NOT NULL;

CREATE TABLE public.content_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id UUID REFERENCES public.content_articles(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  actor_email TEXT NOT NULL,
  details JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX content_audit_article_idx ON public.content_audit_log (article_id, created_at DESC);

CREATE TABLE public.content_studio_settings (
  id SMALLINT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  daily_draft_count INTEGER NOT NULL DEFAULT 2 CHECK (daily_draft_count BETWEEN 1 AND 2),
  default_author TEXT NOT NULL DEFAULT 'Suneel Kumar Kola',
  prompt_version TEXT NOT NULL DEFAULT 'blog-v1',
  updated_by_email TEXT NOT NULL DEFAULT 'system@eazydatafix.com',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO public.content_studio_settings (id) VALUES (1)
ON CONFLICT (id) DO NOTHING;

CREATE OR REPLACE FUNCTION public.content_studio_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER content_articles_updated_at
BEFORE UPDATE ON public.content_articles
FOR EACH ROW EXECUTE FUNCTION public.content_studio_set_updated_at();

CREATE TRIGGER content_studio_settings_updated_at
BEFORE UPDATE ON public.content_studio_settings
FOR EACH ROW EXECUTE FUNCTION public.content_studio_set_updated_at();

ALTER TABLE public.content_articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_generation_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_studio_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can read published and due scheduled articles"
ON public.content_articles
FOR SELECT
TO anon, authenticated
USING (
  status = 'published'
  OR (status = 'scheduled' AND scheduled_at IS NOT NULL AND scheduled_at <= now())
);

GRANT SELECT ON public.content_articles TO anon, authenticated;
GRANT ALL ON public.content_articles TO service_role;
GRANT ALL ON public.content_generation_runs TO service_role;
GRANT ALL ON public.content_audit_log TO service_role;
GRANT ALL ON public.content_studio_settings TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.content_audit_log_id_seq TO service_role;